services:
  api-backend:
    build: .
    container_name: my_production_backend
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    ports:
      - 8000:8000
